// languages/sw.ts
export default {
  header: "Karibu kwenye Umwagiliaji Mahiri",
  location: "Eneo",
  selectLocation: "Chagua Eneo",
  crop: "Mazao",
  selectCrop: "Chagua Mazao",
  plantingDate: "Tarehe ya Kupanda",
  farmSize: "Ukubwa wa Shamba (ekari)",
  enterFarmSize: "Ingiza ukubwa wa shamba",
  soilType: "Aina ya Udongo",
  selectSoilType: "Chagua Aina ya Udongo",
  submitButton: "Tengeneza Ratiba ya Umwagiliaji",
  resultsHeader: "Ratiba ya Umwagiliaji",
  stage: "Hatua",
  waterPerAcre: "Maji/ekari",
  liters: "lita",
  totalWater: "Jumla ya maji",
  kasapo: "Kasapo",
  bangalala: "Bangalala",
  north: "Kanda ya Kaskazini",
  south: "Kanda ya Kusini",
  east: "Kanda ya Mashariki",
  west: "Kanda ya Magharibi",
  central: "Kanda ya Kati",
  maize: "Mahindi",
  wheat: "Ngano",
  rice: "Mpunga",
  beans: "Maharage",
  tomatoes: "Nyanya",
  clay: "Udongo wa mfinyanzi",
  sandy: "Udongo wa mchanga",
  loamy: "Udongo wa tifutifu",
  invalidFarmSize: "Tafadhali ingiza ukubwa sahihi wa shamba",
  fillAllFields: "Tafadhali jaza sehemu zote",
  scheduleError: "Imeshindikana kutengeneza ratiba ya umwagiliaji"
  };